
all:
	/usr/bin/gcc -Wall -Ilibfreenect/include -Ilibfreenect/wrappers/c_sync -o mapkin.c.o -c mapkin.c
	/usr/bin/gcc -Wall mapkin.c.o -o mapkin -rdynamic libfreenect/build/lib/libfreenect_sync.so.0.0.1 -lGLU -lGL -lSM -lICE -lX11 -lXext -lglut -lXmu -lXi -lpthread -lm libfreenect/build/lib/libfreenect.so.0.0.1 -lusb-1.0 -Wl,-rpath,libfreenect/build/lib:

clean:
	rm *.o

